//
//  ChannelListPresenterTests.swift
//  ChatChat
//
//  Created by Kenneth Yip on 2017-12-07.
//  Copyright (c) 2017 Razeware LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ChatChat
import XCTest

class ChannelListPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ChannelListPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupChannelListPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupChannelListPresenter()
  {
    sut = ChannelListPresenter()
  }
  
  // MARK: Test doubles
  
  class ChannelListDisplayLogicSpy: ChannelListDisplayLogic
  {
    var displayUpdatedChannelListCalled = false
    
    func displayUpdatedChannelList(viewModel: ChannelList.FetchChannels.ViewModel)
    {
      displayUpdatedChannelListCalled = true
    }
    
    func presentError(viewModel: ChannelList.Error.ViewModel) {
        
    }

  }
  
  // MARK: Tests
  
  func testUpdatedChannelList()
  {
    // Given
    let spy = ChannelListDisplayLogicSpy()
    sut.viewController = spy
    let response = ChannelList.FetchChannels.Response(channels: [Seeds.Channels.swiftChannel])
    
    // When
    sut.presentUpdatedChannelList(response: response)
    
    // Then
    XCTAssertTrue(spy.displayUpdatedChannelListCalled, "presentUpdatedChannelList(response:) should ask the view controller to display the result")
  }
}
