//
//  ChannelListPresenter.swift
//  ChatChat
//
//  Created by Kenneth Yip on 2017-11-23.
//  Copyright (c) 2017 Razeware LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChannelListPresentationLogic
{
    func presentUpdatedChannelList(response: ChannelList.FetchChannels.Response)
    func presentError(response:ChannelList.Error.Response)
}

class ChannelListPresenter: ChannelListPresentationLogic
{
  weak var viewController: ChannelListDisplayLogic?
  
  // MARK: Do something
    func presentUpdatedChannelList(response: ChannelList.FetchChannels.Response) {
        let viewModel = ChannelList.FetchChannels.ViewModel(displayedChannels: response.channels)
        viewController?.displayUpdatedChannelList(viewModel: viewModel)
    }
    
    func presentError(response:ChannelList.Error.Response) {
        let viewModel = ChannelList.Error.ViewModel(errorMessage: response.errorMessage)
        viewController?.presentError(viewModel: viewModel)
    }
}
