//
//  LoginModels.swift
//  ChatChat
//
//  Created by Kenneth Yip on 2017-11-23.
//  Copyright (c) 2017 Razeware LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum SignIn
  {
    struct Request
    {
        var senderName:String?
    }
    struct Response
    {
        var success:Bool
        var errorString:String?
    }
    struct ViewModel
    {
        var success:Bool
        var errorString:String?
    }
  }
    
    enum Navigation
    {
        struct Request
        {
            var senderDisplayName:String
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
}
