//
//  LoginRouter.swift
//  ChatChat
//
//  Created by Kenneth Yip on 2017-11-23.
//  Copyright (c) 2017 Razeware LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func performSegue(withIdentifier identifier: String, sender: Any?)
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Routing
  
    func performSegue(withIdentifier identifier: String, sender: Any?) {
        viewController?.performSegue(withIdentifier: "LoginToChat", sender: nil)
    }
    
  func routeToLoginToChat(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
        let navVc = segue.destination as! UINavigationController
        let channelVc = navVc.viewControllers.first as! ChannelListViewController
        var destinationDS = channelVc.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    }
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: LoginDataStore, destination: inout ChannelListDataStore)
  {
    destination.senderDisplayName = source.senderDisplayName
  }
}
