//
//  LoginWorker.swift
//  ChatChat
//
//  Created by Kenneth Yip on 2017-11-23.
//  Copyright (c) 2017 Razeware LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    var loginApi: LoginAPIProtocol
    var senderId: String {
        get {
            return loginApi.senderId
        }
    }

    init(loginApi: LoginAPIProtocol)
    {
        self.loginApi = loginApi
    }
    
    func signInAnonymously(onComplete: @escaping (Bool, BackendNetworkError?) -> Void) {
        self.loginApi.signInAnonymously(onComplete: {(success: Bool, someError: BackendNetworkError?) -> Void in
            onComplete (success, someError)
        })
    }
}

protocol LoginAPIProtocol {
    var senderId: String {get}
    func signInAnonymously(onComplete: @escaping (Bool, BackendNetworkError?) -> Void)
}
