//
//  LoginPresenter.swift
//  ChatChat
//
//  Created by Kenneth Yip on 2017-11-23.
//  Copyright (c) 2017 Razeware LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentChannelList(loginResponseModel:Login.SignIn.Response)
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    func presentChannelList(loginResponseModel:Login.SignIn.Response) {
        
        let loginViewModel = Login.SignIn.ViewModel(success: loginResponseModel.success, errorString:loginResponseModel.errorString)
        
        viewController?.presentChannelList(viewModel: loginViewModel)
    }
}
