//
//  LoginPresenterTests.swift
//  ChatChat
//
//  Created by Kenneth Yip on 2017-12-05.
//  Copyright (c) 2017 Razeware LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ChatChat
import XCTest

class LoginPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: LoginPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupLoginPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupLoginPresenter()
  {
    sut = LoginPresenter()
  }
  
  // MARK: Test doubles
  
  class LoginDisplayLogicSpy: LoginDisplayLogic
  {
    var presentChannelListCalled = false
    
    func presentChannelList(viewModel: Login.SignIn.ViewModel)
    {
      presentChannelListCalled = true
    }
  }

  // MARK: Tests
  
  func testPresentChannelList()
  {
    // Given
    let spy = LoginDisplayLogicSpy()
    sut.viewController = spy
    let response = Login.SignIn.Response(success:true, errorString: nil)
    
    // When
    sut.presentChannelList(loginResponseModel: response)
    
    // Then
    XCTAssertTrue(spy.presentChannelListCalled, "presentChannelList(response:) should ask the view controller to presentChannelList")
  }
}
